export const LOAD_INGREDIENTS_REQUEST = 'LOAD_INGREDIENTS_REQUEST';
export const LOAD_INGREDIENTS_FAILED = 'LOAD_INGREDIENTS_FAILED';
export const LOAD_INGREDIENTS_SUCCESS = 'LOAD_INGREDIENTS_SUCCESS';
export const PLUS_V = 'PLUS_V';
export const MINUS_V = 'MINUS_V';
export const RESET_V = 'RESET_V';

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';

export const ADD_BUN = 'ADD_BUN';
export const ADD_INNER = 'ADD_INNER';
export const PLUS_COST = 'PLUS_COST';
export const MINUS_COST = 'MINUS_COST';
export const RESET_BUN_COST = 'RESET_BUN_COST';
export const REMOVE_BUN = 'REMOVE_BUN';
export const REMOVE_INNER = 'REMOVE_INNER';
export const SORT_INGREDIENTS = 'SOR_INGREDIENTS'; 
export const RESET_CONSRUCTOR = 'RESET_CONSRUCTOR';

export const ADD_MODAL_INGREDIENT = 'ADD_MODAL_INGREDIENT';
export const REMOVE_MODAL_INGREDIENT = 'REMOVE_MODAL_INGREDIENT';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const RESET_ORDER = 'RESET_ORDER';

export const CHANGE_TAB = 'CHANGE_TAB';

export const AUTH_CHECKED = 'AUTH_CHECKED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
