export const LOAD_INGREDIENTS_REQUEST = 'LOAD_INGREDIENTS_REQUEST';
export const LOAD_INGREDIENTS_FAILED = 'LOAD_INGREDIENTS_FAILED';
export const LOAD_INGREDIENTS_SUCCESS = 'LOAD_INGREDIENTS_SUCCESS';
export const PLUS_V = 'PLUS_V';
export const MINUS_V = 'MINUS_V';

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';

export const ADD_BUN = 'ADD_BUN';
export const ADD_INNER = 'ADD_INNER';
export const PLUS_COST = 'PLUS_COST';
export const MINUS_COST = 'MINUS_COST';
export const RESET_BUN_COST = 'RESET_BUN_COST';
export const REMOVE_BUN = 'REMOVE_BUN';
export const REMOVE_INNER = 'REMOVE_INNER';
export const SORT_INGREDIENTS = 'SOR_INGREDIENTS'; 

export const ADD_MODAL_INGREDIENT = 'ADD_MODAL_INGREDIENT';
export const REMOVE_MODAL_INGREDIENT = 'REMOVE_MODAL_INGREDIENT';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const RESET_ORDER = 'RESET_ORDER';

export const CHANGE_TAB = 'CHANGE_TAB';
